param(
    [Parameter(Mandatory = $true)]
    [string]$CertificatePath,

    [string]$OutputPath = "$([Environment]::GetFolderPath("Desktop"))\lesaria_distribution.p12",

    [string]$Password = "lesaria-testflight"
)

$ErrorActionPreference = "Stop"

if (!(Test-Path $CertificatePath)) {
    throw "Certificate not found: $CertificatePath"
}

$importOutput = certutil -user -addstore My $CertificatePath
$hashLine = $importOutput | Select-String -Pattern "Zertifikathash\\(sha1\\):|Cert Hash\\(sha1\\):" | Select-Object -Last 1
if ($null -eq $hashLine) {
    throw "Could not read imported certificate thumbprint from certutil output."
}

$thumbprint = (($hashLine -split ":", 2)[1] -replace "\s", "").ToUpperInvariant()
certutil -user -repairstore My $thumbprint | Out-Host

$certificate = Get-ChildItem Cert:\CurrentUser\My\$thumbprint -ErrorAction Stop
if (!$certificate.HasPrivateKey) {
    throw "Imported certificate has no private key. Make sure the .cer was created from the CSR generated by create_distribution_csr.ps1 on this Windows user."
}

$securePassword = ConvertTo-SecureString -String $Password -Force -AsPlainText
Export-PfxCertificate -Cert $certificate -FilePath $OutputPath -Password $securePassword -Force | Out-Null

$base64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($OutputPath))
$base64 | Set-Clipboard

Write-Host "Exported certificate: $($certificate.Subject)"
Write-Host "Thumbprint: $($certificate.Thumbprint)"
Write-Host "Created P12: $OutputPath"
Write-Host "P12 password: $Password"
Write-Host "BUILD_CERTIFICATE_BASE64 copied to clipboard."
