param(
    [Parameter(Mandatory = $true)]
    [string]$CertificatePath,

    [string]$OutputPath = "$([Environment]::GetFolderPath("Desktop"))\lesaria_distribution.p12",

    [string]$Password = "lesaria-testflight"
)

$ErrorActionPreference = "Stop"

if (!(Test-Path $CertificatePath)) {
    throw "Certificate not found: $CertificatePath"
}

$before = @(Get-ChildItem Cert:\CurrentUser\My | ForEach-Object { $_.Thumbprint })

certreq -accept $CertificatePath | Out-Host

$after = @(Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.HasPrivateKey })
$certificate = $after |
    Where-Object { $before -notcontains $_.Thumbprint } |
    Sort-Object NotBefore -Descending |
    Select-Object -First 1

if ($null -eq $certificate) {
    $certificate = $after |
        Where-Object { $_.Issuer -like "*Apple*" -or $_.Subject -like "*Apple Distribution*" -or $_.Subject -like "*Lesaria Distribution*" } |
        Sort-Object NotBefore -Descending |
        Select-Object -First 1
}

if ($null -eq $certificate) {
    throw "Could not find an installed certificate with a private key. Make sure the .cer was created from the CSR generated by create_distribution_csr.ps1."
}

$securePassword = ConvertTo-SecureString -String $Password -Force -AsPlainText
Export-PfxCertificate -Cert $certificate -FilePath $OutputPath -Password $securePassword -Force | Out-Null

$base64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($OutputPath))
$base64 | Set-Clipboard

Write-Host "Exported certificate: $($certificate.Subject)"
Write-Host "Thumbprint: $($certificate.Thumbprint)"
Write-Host "Created P12: $OutputPath"
Write-Host "P12 password: $Password"
Write-Host "BUILD_CERTIFICATE_BASE64 copied to clipboard."
